### ISSUE TITLE
Crear ABM de puntaje de cada tipo de servicio para cada año

### ISSUE THREAD

**Issue by jdottori** [Unicen-Tupar/bomberos#178]
Cada año se puede cambiar el puntaje asignado a cada categoría de las puntuaciones (ASIST OBLIG, ACCID, DEDIC, ASIST  GUARDIAS, ETC). Actualmente están hardcodeados los puntajes de cada una. El 1-Enero de cada año estos puntajes cambian.  Hacer TDD.
- [ ] Implementar test unitarios del ABM
- [ ] Crear un ABM para esto
- [ ] Usar estos puntajes según el año para el cálculo de puntuación
- [ ] Actualizar tests realizados en #174 

### Documentación pertinente:
https://docs.google.com/document/d/1KjYDUfHdsQI5nGtiMuLMVLTMk6I7yuSQoFHA394NX1Y/edit

**Comment by SSAAMMAA** [comment]
Entiendo que tengo que crear  una tabla nueva en la base de datos que contenga por cada año, en cada categoria, la puntuacion y sean modificables cuando se ingrese a '/puntuacion/variables' y una tabla que tenga las categorias para modificar, me pueden confirmar esto? Saludos @Pablo-Rivera @ferochoteco

**Comment by Pablo-Rivera** [comment]
Hola  @SSAAMMAA, la tabla ya existe es [variables_table.php](https://github.com/Unicen-Tupar/bomberos/blob/master/database/migrations/2017_07_17_134745_create_variables_table.php) calculo que lo que se refiere javi es que almacenes la puntuación de cada año. 
Nosotros solo la creamos y la usamos como variable osea que estamos modificando siempre el mismo puntaje  y no queda registro en el tiempo también forzamos la creación cuando con valores cuando se crea el primer [usuario](https://github.com/Unicen-Tupar/bomberos/blob/master/app/Http/Controllers/Auth/RegisterController.php) linea 74
El template para modificar esa puntuación se encuentra en la vista de [puntuacion/variables.blade.php](https://github.com/Unicen-Tupar/bomberos/blob/master/resources/views/puntuacion/variables.blade.php).
Como lo piden tendrías que hacer un sistema que a la hora de puntuar tenga las variable del año seleccionado y hacer los controles de que si en un año ya se puntuó con esos valores no se permitan modificarlos dado que estarías puntuando con diferentes criterios a los bomberos, lo mismo para la eliminación.
No se a que te referís con la categoría para modificar.
Saludos
