### ISSUE TITLE
Crear BM de usuarios

### ISSUE THREAD

**Issue by perezale** [Unicen-Tupar/bomberos#198]
Además del Alta de usuario se debe permitir dar de baja y modificar usuarios existentes. 

Implementar la baja haciendo un borrado lógico (agregando una columna de borrado en Usuario)

**Comment by emmanuel-flores** [comment]
Reabriendo, se cerro incorrectamente con un commit correspondiente a #173

**Comment by ignaciojonas** [comment]
Cerrando este issue repetido #176
