### ISSUE TITLE
ABM Planilla responsabilidades

### ISSUE THREAD

**Issue by perezale** [Unicen-Tupar/bomberos#261]
Permitir crear, modificar y borrar planillas según adjunto, incluyendo generacion de grupos de vehiculos materiales y edificios.

[planilla_responsabilidades.pdf](https://github.com/Unicen-Tupar/bomberos/files/1446560/planilla_responsabilidades.1.pdf)

Notas:
Representar los grupos de vehículos, materiales y edifcios como un único campo de texto

**Comment by jdottori** [comment]
Mariel, esta es la opcion que te decia de JS: 
https://stackoverflow.com/questions/14853779/adding-input-elements-dynamically-to-form
Fijate mezclando la respuesta que gano y la siguiente. La primera esta Ok, pero hace las cosas con name ="member"+i. la segunda esta mejor, pero usa Jquery. Aunque creo que con eso no hay probelma en bomberos porque ya se usaba.

**Comment by mangieri** [comment]
Hola Javi, ahora miro y cualquier duda mando mail a la lista. Gracias!
